[package]
name = "inception-derive-gen"
description = "Shared derive expansion logic for Inception-compatible proc macros"
authors = ["Nick Senger <dev@nsenger.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/nicksenger/inception"
rust-version = "1.84"
version = "0.1.0"

[features]
default = ["opt-in"]
opt-in = []

[dependencies]
proc-macro-crate = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { features = ["full"], workspace = true }
